import type { Metadata } from 'next';
import { VercelToolbar } from '@vercel/toolbar/next';
import { Analytics } from '@vercel/analytics/next';

import './globals.css';

export const metadata: Metadata = {
  title: 'Shirt Shop',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const shouldInjectToolbar = process.env.NODE_ENV === 'development';
  return (
    <html lang="en">
      <body className="">
        {children}

        {shouldInjectToolbar && <VercelToolbar />}
        <Analytics />
      </body>
    </html>
  );
}
